// <auto-generated />
using System;
using Celticstech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Celticstech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528004720_AjusteTipoRecomendacao")]
    partial class AjusteTipoRecomendacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Celticstech.Models.Agricultor", b =>
                {
                    b.Property<int>("IdAgricultor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAgricultor"));

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("NomeAgricultor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QtdeDependentes")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("IdAgricultor");

                    b.ToTable("Agricultores");
                });

            modelBuilder.Entity("Celticstech.Models.Associacao", b =>
                {
                    b.Property<int>("IdAssociacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAssociacao"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("NomeAssociacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SiglaAssociacao")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("IdAssociacao");

                    b.HasIndex("IdRegiao");

                    b.ToTable("Associacoes");
                });

            modelBuilder.Entity("Celticstech.Models.Cultivo", b =>
                {
                    b.Property<int>("IdCultivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCultivo"));

                    b.Property<string>("CategoriaCultivo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Intermitencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NomeCultivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PorteCultivo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("TempoColheita")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("VidaUtil")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdCultivo");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("Celticstech.Models.Recomendacao", b =>
                {
                    b.Property<int>("IdRecomendacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecomendacao"));

                    b.Property<DateTime>("DataRecAsc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAssociacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdCultivo")
                        .HasColumnType("integer");

                    b.Property<string>("Orientacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoRecomendacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRecomendacao");

                    b.HasIndex("IdAssociacao");

                    b.HasIndex("IdCultivo");

                    b.ToTable("Recomendacoes");
                });

            modelBuilder.Entity("Celticstech.Models.Regiao", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegiao"));

                    b.Property<string>("NomeRegiao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UfRegiao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdRegiao");

                    b.ToTable("Regioes");
                });

            modelBuilder.Entity("Celticstech.Models.Associacao", b =>
                {
                    b.HasOne("Celticstech.Models.Regiao", "Regiao")
                        .WithMany("Associacoes")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Celticstech.Models.Recomendacao", b =>
                {
                    b.HasOne("Celticstech.Models.Associacao", "Associacao")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("IdAssociacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Celticstech.Models.Cultivo", "Cultivo")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("IdCultivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associacao");

                    b.Navigation("Cultivo");
                });

            modelBuilder.Entity("Celticstech.Models.Associacao", b =>
                {
                    b.Navigation("Recomendacoes");
                });

            modelBuilder.Entity("Celticstech.Models.Cultivo", b =>
                {
                    b.Navigation("Recomendacoes");
                });

            modelBuilder.Entity("Celticstech.Models.Regiao", b =>
                {
                    b.Navigation("Associacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
